-- Migration: create_enums
-- All PostgreSQL enum types used by the application

CREATE TYPE "UserRole" AS ENUM ('SUPER_ADMIN', 'GYM_OWNER', 'MANAGER', 'RECEPTIONIST', 'TRAINER', 'MEMBER');
CREATE TYPE "UserStatus" AS ENUM ('ACTIVE', 'INACTIVE', 'SUSPENDED', 'PENDING_VERIFICATION');
CREATE TYPE "SubscriptionPlanType" AS ENUM ('SINGLE_GYM', 'TWO_GYMS', 'FIVE_GYMS', 'UNLIMITED');
CREATE TYPE "SubscriptionStatus" AS ENUM ('TRIAL', 'ACTIVE', 'EXPIRED', 'CANCELLED', 'PAST_DUE');
CREATE TYPE "MembershipStatus" AS ENUM ('ACTIVE', 'FROZEN', 'EXPIRED', 'CANCELLED', 'PENDING');
CREATE TYPE "MembershipBillingCycle" AS ENUM ('MONTHLY', 'QUARTERLY', 'YEARLY');
CREATE TYPE "AttendanceType" AS ENUM ('CHECK_IN', 'CHECK_OUT');
CREATE TYPE "AttendanceSource" AS ENUM ('QR_CODE', 'PUNCH', 'FRONTDESK', 'MOBILE', 'BIOMETRIC');
CREATE TYPE "EventType" AS ENUM ('ZUMBA', 'YOGA', 'OUTDOOR', 'WORKSHOP', 'PERSONAL_TRAINING', 'OTHER');
CREATE TYPE "LeadStatus" AS ENUM ('NEW', 'CONTACTED', 'TRIAL', 'FOLLOW_UP', 'CONVERTED', 'LOST');
CREATE TYPE "NotificationChannel" AS ENUM ('EMAIL', 'SMS', 'PUSH', 'WHATSAPP');
CREATE TYPE "NotificationStatus" AS ENUM ('PENDING', 'SENT', 'FAILED');
CREATE TYPE "PaymentStatus" AS ENUM ('PENDING', 'COMPLETED', 'FAILED', 'REFUNDED');
CREATE TYPE "InvoiceStatus" AS ENUM ('DRAFT', 'ISSUED', 'PAID', 'OVERDUE', 'CANCELLED');
